### Добавление новых студентов
POST http://localhost:8080/student
Content-Type: application/json

{
  "id": 0,
  "name": "James",
  "age": 16,
  "faculty": {
    "id": 2,
    "name": "string",
    "color": "string"
  }
}

### Получение студента по id
GET http://localhost:8080/student/1

### Изменение данных студента
PUT http://localhost:8080/student

{
  "name": "string",
  "age": 0,
}

### Удаление студента
DELETE http://localhost:8080/student/1

### Получение всех студентов в определённом возрасте
GET http://localhost:8080/student/findByAge?age=16

### Получение всех студентов в возрасте от и до
GET http://localhost:8080/student/findByAgeBetween?minAge=15&maxAge=23

### Получение факультета студента
GET http://localhost:8080/student/10/faculty

### Получение количества студентов в школе
GET http://localhost:8080/student/countAll

### Получение среднего возраста студентов в школе
GET http://localhost:8080/student/getAverageAge

### Получение пяти последних студентов
GET http://localhost:8080/student/getLastStudents


